platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'HaoTongZhi' do
    pod 'AFNetworking'
    pod 'Masonry'
    pod 'SVProgressHUD'
    pod 'MJExtension'
    pod 'MJRefresh'
end